/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_struct = 2,
  anon_sym_trait = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_SEMI = 9,
  sym_identifier = 10,
  sym_number = 11,
  sym_source_file = 12,
  sym__statement = 13,
  sym_function_definition = 14,
  sym_struct_definition = 15,
  sym_trait_definition = 16,
  sym_parameter_list = 17,
  sym_block = 18,
  sym_expression_statement = 19,
  sym__expression = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_parameter_list_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_struct] = "struct",
  [anon_sym_trait] = "trait",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_function_definition] = "function_definition",
  [sym_struct_definition] = "struct_definition",
  [sym_trait_definition] = "trait_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_block] = "block",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_trait] = anon_sym_trait,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_function_definition] = sym_function_definition,
  [sym_struct_definition] = sym_struct_definition,
  [sym_trait_definition] = sym_trait_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_block] = sym_block,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_trait_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 5,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 17,
  [18] = 12,
  [19] = 14,
  [20] = 15,
  [21] = 13,
  [22] = 17,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 26,
  [34] = 32,
  [35] = 29,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 37,
  [44] = 42,
  [45] = 45,
  [46] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        '(', 6,
        ')', 8,
        ',', 7,
        ';', 11,
        'f', 15,
        's', 20,
        't', 16,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_trait);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_trait] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym__statement] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_struct_definition] = STATE(4),
    [sym_trait_definition] = STATE(4),
    [sym_expression_statement] = STATE(4),
    [sym__expression] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
    [anon_sym_struct] = ACTIONS(7),
    [anon_sym_trait] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_struct_definition] = STATE(2),
    [sym_trait_definition] = STATE(2),
    [sym_expression_statement] = STATE(2),
    [sym__expression] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_struct] = ACTIONS(18),
    [anon_sym_trait] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(24),
    [sym_identifier] = ACTIONS(26),
    [sym_number] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_struct_definition] = STATE(3),
    [sym_trait_definition] = STATE(3),
    [sym_expression_statement] = STATE(3),
    [sym__expression] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(24),
    [anon_sym_fn] = ACTIONS(32),
    [anon_sym_struct] = ACTIONS(35),
    [anon_sym_trait] = ACTIONS(38),
    [sym_identifier] = ACTIONS(41),
    [sym_number] = ACTIONS(44),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_struct_definition] = STATE(3),
    [sym_trait_definition] = STATE(3),
    [sym_expression_statement] = STATE(3),
    [sym__expression] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_fn] = ACTIONS(5),
    [anon_sym_struct] = ACTIONS(7),
    [anon_sym_trait] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_struct_definition] = STATE(2),
    [sym_trait_definition] = STATE(2),
    [sym_expression_statement] = STATE(2),
    [sym__expression] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_struct] = ACTIONS(51),
    [anon_sym_trait] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [sym_number] = ACTIONS(59),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym_struct_definition] = STATE(5),
    [sym_trait_definition] = STATE(5),
    [sym_expression_statement] = STATE(5),
    [sym__expression] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_struct] = ACTIONS(51),
    [anon_sym_trait] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(61),
    [sym_identifier] = ACTIONS(57),
    [sym_number] = ACTIONS(59),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(8),
    [sym_function_definition] = STATE(8),
    [sym_struct_definition] = STATE(8),
    [sym_trait_definition] = STATE(8),
    [sym_expression_statement] = STATE(8),
    [sym__expression] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_struct] = ACTIONS(51),
    [anon_sym_trait] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(63),
    [sym_identifier] = ACTIONS(57),
    [sym_number] = ACTIONS(59),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_struct_definition] = STATE(2),
    [sym_trait_definition] = STATE(2),
    [sym_expression_statement] = STATE(2),
    [sym__expression] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_struct] = ACTIONS(51),
    [anon_sym_trait] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(65),
    [sym_identifier] = ACTIONS(57),
    [sym_number] = ACTIONS(59),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(69), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(67), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [14] = 3,
    ACTIONS(73), 1,
      anon_sym_SEMI,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(67), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [28] = 2,
    ACTIONS(77), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(75), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [39] = 2,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(81), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [50] = 2,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(85), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [61] = 2,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(89), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [72] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(93), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [83] = 2,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(75), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [94] = 2,
    ACTIONS(97), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(95), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [105] = 2,
    ACTIONS(79), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(81), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [116] = 2,
    ACTIONS(87), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(89), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [127] = 2,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(93), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [138] = 2,
    ACTIONS(83), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(85), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [149] = 2,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(95), 4,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_trait,
      sym_identifier,
  [160] = 3,
    ACTIONS(99), 1,
      anon_sym_COMMA,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_parameter_list_repeat1,
  [170] = 3,
    ACTIONS(99), 1,
      anon_sym_COMMA,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_parameter_list_repeat1,
  [180] = 3,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_parameter_list_repeat1,
  [190] = 2,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_block,
  [197] = 2,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    ACTIONS(114), 1,
      sym_identifier,
  [204] = 1,
    ACTIONS(108), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [209] = 2,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_parameter_list,
  [216] = 2,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_block,
  [223] = 2,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_block,
  [230] = 2,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_block,
  [237] = 2,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_block,
  [244] = 2,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
  [251] = 2,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_parameter_list,
  [258] = 1,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
  [262] = 1,
    ACTIONS(122), 1,
      sym_identifier,
  [266] = 1,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
  [270] = 1,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
  [274] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [278] = 1,
    ACTIONS(130), 1,
      sym_identifier,
  [282] = 1,
    ACTIONS(132), 1,
      sym_identifier,
  [286] = 1,
    ACTIONS(134), 1,
      sym_identifier,
  [290] = 1,
    ACTIONS(136), 1,
      sym_identifier,
  [294] = 1,
    ACTIONS(138), 1,
      sym_identifier,
  [298] = 1,
    ACTIONS(140), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 14,
  [SMALL_STATE(11)] = 28,
  [SMALL_STATE(12)] = 39,
  [SMALL_STATE(13)] = 50,
  [SMALL_STATE(14)] = 61,
  [SMALL_STATE(15)] = 72,
  [SMALL_STATE(16)] = 83,
  [SMALL_STATE(17)] = 94,
  [SMALL_STATE(18)] = 105,
  [SMALL_STATE(19)] = 116,
  [SMALL_STATE(20)] = 127,
  [SMALL_STATE(21)] = 138,
  [SMALL_STATE(22)] = 149,
  [SMALL_STATE(23)] = 160,
  [SMALL_STATE(24)] = 170,
  [SMALL_STATE(25)] = 180,
  [SMALL_STATE(26)] = 190,
  [SMALL_STATE(27)] = 197,
  [SMALL_STATE(28)] = 204,
  [SMALL_STATE(29)] = 209,
  [SMALL_STATE(30)] = 216,
  [SMALL_STATE(31)] = 223,
  [SMALL_STATE(32)] = 230,
  [SMALL_STATE(33)] = 237,
  [SMALL_STATE(34)] = 244,
  [SMALL_STATE(35)] = 251,
  [SMALL_STATE(36)] = 258,
  [SMALL_STATE(37)] = 262,
  [SMALL_STATE(38)] = 266,
  [SMALL_STATE(39)] = 270,
  [SMALL_STATE(40)] = 274,
  [SMALL_STATE(41)] = 278,
  [SMALL_STATE(42)] = 282,
  [SMALL_STATE(43)] = 286,
  [SMALL_STATE(44)] = 290,
  [SMALL_STATE(45)] = 294,
  [SMALL_STATE(46)] = 298,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trait_definition, 3, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trait_definition, 3, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 3, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 3, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mojo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mojo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
